### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Sabyyy**
Formatted for better look

### CODE REVIEW

**Comment by Sabyyy** [comment]
Man it looked cooler in the text.

**Comment by Chicken** [comment]
Man it really looks like you farming pull requests for hacktoberfest, I would usually be fine but such a small change in a readme of a damn website? Yeah no.

**Comment by Chicken** [comment]
Also changed the most important part of the whole thing "my shit" to "my stuff".

**Comment by Sabyyy** [comment]
:-(  I'm done with 4 PRs for Hacktoberfest tho. But yeah, I kinda wanted to keep it clean so made the word change. Nvm.

**Pull request closed without merging**
